# .repo.toml

# TODO: mirrors later

[about]
description = "domain registration backend"
#topics = []
license = "GPL-2.0-only"

[urls]
git_ssh = "git@github.com:fini-net/macaw.git"
web_url = "https://github.com/fini-net/macaw"

[flags]
claude = true
claude-review = true
copilot-review = true
